// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOQAncFsC0yjboDcfQ1ys9fWgwsaRcb6U',
    appId: '1:605574062035:web:132c0168f43d4d80339926',
    messagingSenderId: '605574062035',
    projectId: 'chat-app-98923',
    authDomain: 'chat-app-98923.firebaseapp.com',
    storageBucket: 'chat-app-98923.appspot.com',
    measurementId: 'G-62FNP9L79M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFmQWndxXWk648CY28WhJo8Obi02-TrlA',
    appId: '1:605574062035:android:f3ec12830ad2f318339926',
    messagingSenderId: '605574062035',
    projectId: 'chat-app-98923',
    storageBucket: 'chat-app-98923.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLRN1Ghd8y37x4xFISwWx7djzdxxOEchs',
    appId: '1:605574062035:ios:b7025ded9cdda9e9339926',
    messagingSenderId: '605574062035',
    projectId: 'chat-app-98923',
    storageBucket: 'chat-app-98923.appspot.com',
    iosBundleId: 'com.example.chattingTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLRN1Ghd8y37x4xFISwWx7djzdxxOEchs',
    appId: '1:605574062035:ios:b7025ded9cdda9e9339926',
    messagingSenderId: '605574062035',
    projectId: 'chat-app-98923',
    storageBucket: 'chat-app-98923.appspot.com',
    iosBundleId: 'com.example.chattingTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOQAncFsC0yjboDcfQ1ys9fWgwsaRcb6U',
    appId: '1:605574062035:web:8ffafa9585c0335e339926',
    messagingSenderId: '605574062035',
    projectId: 'chat-app-98923',
    authDomain: 'chat-app-98923.firebaseapp.com',
    storageBucket: 'chat-app-98923.appspot.com',
    measurementId: 'G-N78YBVWJW8',
  );
}
